name: Flutter analyzing

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.1'

    - name: Get dependencies
      run: flutter pub get

    - name: Run analyse
      run: flutter analyse
